FeriyalStory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include, re_path
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace="social")),
    path('', include('status.urls'), name="index"),
    path('', include('store.urls'), name="buku"),
]

status/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'status'

urlpatterns = [
    path('', views.landingpage, name="landingpage"),
    path('addstatus', views.addstatus, name="addstatus"),
    path('deletestatus', views.deletestatus, name="deletestatus"),
    path('profil', views.profil, name="profil"),
    path('berlangganan', views.berlangganan, name="berlangganan"),
    path('pengecekan', views.pengecekan, name="pengecekan"),
    path('berhasil', views.berhasil, name="berhasil"),
    path('listsubscriber', views.listsubscriber, name="listsubscriber"),
    path('jsonsubscriber', views.jsonsubscriber, name="jsonsubscriber"),
    path('pengecekanpassword', views.pengecekanpassword, name="pengecekanpassword")
]

store/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'store'

urlpatterns = [
    path('buku', views.buku, name="buku"),
    path('dataBuku/<judul>', views.dataBuku, name="databuku"),
    path('counterFavBuku', views.counterFavBuku, name="counterFavBuku"),
    path('logout/', views.logoutView, name="logout"),
]

status/models.py
from django.db import models

class Status(models.Model):
	status = models.TextField(max_length=300)
	waktu = models.DateTimeField(auto_now_add=True, editable=False, null=False, blank=False)

class Subscriber(models.Model):
	nama = models.CharField(max_length=300)
	email = models.CharField(max_length=100)
	password = models.CharField(max_length=20)

store/models.py
from django.db import models

# Create your models here.

status/forms.py
from django import forms
from .models import Status
from .models import Subscriber

class StatusForm(forms.Form):
	status_attrs = {
		'id': 'id_status',
		'type': 'text',
		'class': 'status-form-input',
		'placeholder': 'Apa yang anda rasakan?'
	}


	status = forms.CharField(label="", required=True, max_length=300, 
		widget=forms.TextInput(attrs=status_attrs))


class SubscriberForm(forms.Form):
	nama_attrs = {
		'id': 'id_nama',
		'type': 'text',
		'class': 'subscriber-form-input',
		'placeholder': ' Nama',
		'required': True
	}

	email_attrs = {
		'id': 'id_email',
		'type': 'email',
		'class': 'subscriber-form-input',
		'placeholder': ' Email',
		'required': True
	}

	password_attrs = {
		'id': 'id_password',
		'type': 'password',
		'class': 'subscriber-form-input',
		'placeholder': ' Password',
		'required': True,
		'min_length': 5
	}

	nama = forms.CharField(widget=forms.TextInput(attrs=nama_attrs))
	email = forms.CharField(widget=forms.EmailInput(attrs=email_attrs))
	password= forms.CharField(widget=forms.PasswordInput(attrs=password_attrs))

status/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import StatusForm
from .models import Status
from .forms import SubscriberForm
from .models import Subscriber
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers



# Create your views here.
response = {}
def landingpage(request):    
    response['author'] = "" #TODO Implement yourname
    allstatus = Status.objects.all()
    response['allstatus'] = allstatus
    html = 'LandingPage.html'
    response['status_form'] = StatusForm
    return render(request, html, response)

def addstatus(request):
    form = StatusForm(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['status'] = request.POST['status']
        perasaan = Status(status=response['status'])
        perasaan.save()
        return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')


def deletestatus(request):
    Status.objects.all().delete()
    return HttpResponseRedirect('/')

def profil(request):
    return render(request, 'Profil.html')

def berlangganan(request):
    response['author'] = ""
    response['subscriber_form'] = SubscriberForm
    return render(request, "Subscribe.html", response)


@csrf_exempt
def pengecekan(request):
    email = request.POST.get("email")
    data = {'not_valid': Subscriber.objects.filter(email__iexact=email).exists()}
    return JsonResponse(data)

@csrf_exempt
def pengecekanpassword(request):
    password = request.POST.get("passwordd")
    email = request.POST.get("email")
    cek_subscriber =  Subscriber.objects.get(email=email)
    print(cek_subscriber.password)
    terhapus = False;
    if cek_subscriber.password == password:
        terhapus = True;
        cek_subscriber.delete()

    data = {'terhapus': terhapus, 'nama':cek_subscriber.nama}
    return JsonResponse(data)

def berhasil(request):
    submited_form = SubscriberForm(request.POST or None)
    if (submited_form.is_valid()):
        cd = submited_form.cleaned_data
        new_subscriber = Subscriber(nama=cd['nama'], password=cd['password'], email=cd['email'])
        new_subscriber.save()
        data = {'nama': cd['nama']}
    return JsonResponse(data)

def listsubscriber(request):
    response = {}
    
    return render(request, "ListSubscriber.html", response)

def jsonsubscriber(request):
    data_json = serializers.serialize('json', Subscriber.objects.all())
    return HttpResponse(data_json, content_type='aplication/json')

store/views.py
from django.shortcuts import render
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.core import serializers
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_exempt
import requests
import json

response = {}
response['counter'] = 0
def dataBuku(request, judul):
	URL = "https://www.googleapis.com/books/v1/volumes?q=" + judul
	get_json = requests.get(URL)
	return HttpResponse(get_json, content_type='application/json')

def buku(request):
	response['counter'] = 0
	if request.user.is_authenticated:
		if 'counter' not in request.session:
			request.session['counter'] = 0
		if 'nama' not in request.session:
			request.session['nama'] = request.user.username
		if 'email' not in request.session:
			request.session['email'] = request.user.email

		count = request.session.get('counter', 0)
		response['counter'] = count
	return render(request, "Buku.html", response)

@csrf_exempt
def counterFavBuku(request):
	if request.user.is_authenticated:
		request.session['counter'] = request.session['counter'] + 1
	return HttpResponse(request.session['counter'], content_type='application/json')

def logoutView(request):
	request.session.flush()
	logout(request)
	return HttpResponseRedirect('/buku')

status/templates/LandingPage.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Hello!</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
	<link href="https://fonts.googleapis.com/css?family=Handlee" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Mali" rel="stylesheet">
	<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/glacial-indifference" type="text/css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  	<script src="{% static 'js/text.js'%}"></script>
	
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body onload="myFunction()" style="margin:0;">
	<div id="loader"></div>


	<div id="konten1" style="display: none;">
		<div class="row">
			<br>
		</div>
		<div class="row">
			<h1 class="display-2 text-center">Hello, Apakabar?</h1>
			<br>
		</div>
		<div class="row">
			<div class="col-4">
				<p></p>
			</div>
			<div class="col-2">
				<a href="{% url 'status:listsubscriber' %}"><button id="list-subscriber" class="btn btn-basic" style="color:white; font-size: 15px; font-style: italic;">List Subscriber</button></a>
			</div>
			<div class="col-4">
				<a href="{% url 'status:berlangganan' %}"><button id="subscribe-me" class="btn btn-basic" style="color:white; font-size: 15px; font-style: italic;">Subscribe me !</button></a>
			</div>
		</div>
	</div>
	<div id="konten2" style="display: none;">
		<div id="formstatus" class="container">
			<div class="square-service-block box-input-form">
				<br>
				<form action="{% url 'status:addstatus' %}" method="POST" style="font-size: 20px;">
		            {% csrf_token %}
		            {{ status_form }} <br>
		            <input id="submit" type="submit" value="Post" class="btn btn-basic button-post" style="color:white; font-size: 15px;">
		        </form>
		        <br>
		        <div class="row">
		        	<div class="col-7">
	    				<a href="{% url 'status:profil' %}" style="margin-left: 15px; font-family: GlacialIndifferenceRegular; font-size: 16px;"> < Profil ku </a>
	    			</div>
	    			<div class="col-5">
	    				<a href="{% url 'store:buku' %}" style="margin-left: 15px; font-family: GlacialIndifferenceRegular; font-size: 16px;">Daftar Buku > </a>
	    			</div>
	    		</div>
	    	</div>
		</div>
		<br><br>

		<div id="liststatus" class="container">
			<div class="square-service-block box-list-status">
				<div class="row">
					<div class="col-6">
						<h3 style="font-family: 'Handlee', cursive;">Status Terkini</h3>
					</div>
					<div class="col-5">
						<br>
						<button id="ubahtema" type="button" class="btn btn-basic button-post" style="font-family: GlacialIndifferenceRegular; color: white;">Ubah Tema</button>
					</div>
				</div>
				<div class="row">
					<table style="width:100%">
	                    {% if allstatus %}
	              
	                        {% for status in allstatus %}
	                        
	                            <div id="boxstatus" class="square-service-block boxstatusawal" style="padding: 10px 10px; border-radius: 10px; font-family: GlacialIndifferenceRegular;">
	                            	<span>{{ status.waktu }} </span><span> {{ status.status }}</span>
		                            
		                        </div>

	                        {% endfor %}

	                        <a href="{% url 'status:deletestatus' %}" style="font-family: GlacialIndifferenceRegular;"><button type="button" class="btn btn-danger">Hapus semua</button></a>

	                    {% else %}
	                    	<br>
	                        <h4 style="font-family: GlacialIndifferenceRegular;">Tidak ada status saat ini.</h4> 
	                    {% endif %}
			        </table>
			    </div>
	    	</div>
		</div>
	</div>
</body>
</html>

status/templates/ListSubscriber.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>List Subscriber</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
	<link href="https://fonts.googleapis.com/css?family=Handlee" rel="stylesheet">	<!-- font -->
	<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/glacial-indifference" type="text/css"/>
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/sweetalert2@7.29.0/dist/sweetalert2.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="{% static 'js/unsubscribe.js'%}"></script>

  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  	
	<!-- Optional: include a polyfill for ES6 Promises for IE11 and Android browser -->
	<script src="https://cdn.jsdelivr.net/npm/promise-polyfill"></script>
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@7.29.0/dist/sweetalert2.all.min.js"></script>
	
<!-- Optional: include a polyfill for ES6 Promises for IE11 and Android browser -->
<script src="https://cdn.jsdelivr.net/npm/promise-polyfill"></script>
</head>
<body>
	<div>
		<div class="row">
			<br>
		</div>
		<div class="row">
			<h1 class="text-center">Daftar Subscriber</h1>
			<br>
		</div>
	</div>

	<div class="row">
		<div class="col-3">
			<p></p>
		</div>
		<div class="col-4">
			<a href="{% url 'status:landingpage' %}"><button class="btn btn-default" style="margin-bottom: 10px; font-family: GlacialIndifferenceRegular; background-color: #ff0055; color: white; width: 100px; height: 40px;">< Beranda</button></a>
		</div>
	</div>

	<div id="tentangsaya" class="container" >
		<div class="square-service-block tentang">
			<h3 class="text-left" style="font-family: 'GlacialIndifferenceRegular'; font-size: 3vw; color: #ff0055;">Subscriber</h3>
			<br>
			<div class="row">
				<div id = "result">
                    
                </div>
			</div>
		</div>

	</div>

	<br><br>
</body>
</html>

status/templates/Profil.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Hello!</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
	<link href="https://fonts.googleapis.com/css?family=Handlee" rel="stylesheet">	<!-- font -->
	<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/glacial-indifference" type="text/css"/>
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="{% static 'js/text.js'%}"></script>

  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
	<div>
		<div class="row">
			<br>
		</div>
		<div class="row">
			<h1 class="text-center">Profil ku</h1>
			<br>
		</div>
	</div>

	<div id="tentangsaya" class="container" >
		<div class="square-service-block tentang">
			<div class="row">
				<div class="col-4">
					<img src="https://image.ibb.co/dORqjz/feriyal_2.jpg" alt="feriyal" class="fotoferiyal">
					<br><br><br>
					<a href="https://drive.google.com/open?id=1mP17f62fiplLrvNHTWQpGJio-46aazBY" target="_blank">
						<button type="button" class="btn btn-basic unduhcv">UNDUH CV</button>
					</a>
					<br><br>
					<button id="ubahtema2" type="button" class="btn btn-basic button-post unduhcv" style="font-family: GlacialIndifferenceRegular; color: white;">Ubah Tema</button>
					<br><br><br>
					<a href="{% url 'status:landingpage' %}" style="font-family: GlacialIndifferenceRegular; font-size: 16px;"> < Kembali</a>
				</div>
				<div class="ini col-8">
					<div class="row atas">
						<h3 class="greet">HAI SAYA FIRRIYAL BIN YAHYA !</h3>
						<h4 class="greytext">Mahasiswa Ilmu Komputer</h4>
						<p class="greeting" style="font-size: 18px;">Hai! Saya Firriyal Bin Yahya. Seorang mahasiswa ilmu komputer di 
	Universitas Indonesia. Saat ini saya sedang menuntut ilmu dan 
	pengetahuan seputar dunia IT. Saya juga sedang mempelajari 
	beberapa bahasa komputer, seperti Java, HTML5, CSS3, 
	Javascript. Disamping itu saya juga memiliki sedikit latar belakang 
	dalam Organisasi dan Kepanitiaan.</p>
					</div>
					<div class="row huruf">
						<div class="col-7">
							<span class="kategori" style="display:inline-block; width: 140px;">Umur</span> <span style="color: black;">18</span><br>
							<span class="kategori" style="display:inline-block; width: 140px;">Alamat	</span> <span>Jl. Kwini 9A, Balekambang,</span><br><span style="display:inline-block; width: 140px;"></span><span>Jakarta Timur</span><br>
							<span class="kategori" style="display:inline-block; width: 140px;">Email</span> <span>feriyalbinyahya@gmail.com</span>
							<br><br>
						</div>
						<div class="col-5">
							<span class="kategori" style="display:inline-block; width: 140px;">Ponsel</span> <span>+6289661156025</span><br>
							<span class="kategori" style="display:inline-block; width: 140px;">Kewarganegaraan</span> <span>Indonesia</span>
						</div>
					</div>
					<div class="row">
						<br><br>
						<p class="kategori huruf">Social Links</p>
						<a href="https://www.facebook.com/fridai17?hc_ref=ARTW9l0ATeWGWL789re7iVld06NJtfKVf7in-4zf4PYY-h8XwSRhbBnjwPqO0bHu8yg&fref=nf&__xts__[0]=68.ARDSJpp810gdBSWI8GE9g6CxJGt2FhiR9e5gPJBuBfAotE5lod1UMMa61-TxO3UjbkxP5kWXWJgt-J9SvZXF-i0KsbzOdmOhDVgX0IeduCd-npyNAPuJFm-Y7P9PA1Rqy0vc_N2WIAmCVtD-8pr0_3H_7GulkOE01ns6_a1BrGpgRVO3fv_x&__tn__=C-R" target="_blank" type="button" class="btn-floating btn-lg btn-fb"><i class="fa fa-facebook"></i></a>
						<a href="https://plus.google.com/102883761578163851191" target="_blank" type="button" class="btn-floating btn-lg btn-gplus"><i class="fa fa-google-plus"></i></a>
						<a href="https://twitter.com/" target="_blank" type="button" class="btn-floating btn-lg btn-tw"><i class="fa fa-twitter"></i></a>
					</div>
				</div>
			</div>
		</div>

	</div>

	<div class="row">
			<br><br><br>
			<h1 class="text-center">Pengalaman ku</h1>
			<br>
	</div>

	<div id="pengalamansaya" class="container">
		<div class="square-service-block pengalaman">
			<button id="aktifitas" class="accordion">Aktivitas</button>
			<div class="panel">
				<br>
				<p>- Kuliah Ilmu Komputer jenjang S1</p>
				<p>- Mengajar siswa sekolahan</p>
				<p>- Menuntut Ilmu Agama</p>
			</div>

			<button class="accordion">Organisasi/Kepanitian</button>
			<div class="panel">
			 	<br>
				<p>- OSIS SMA</p>
				<p>- Sekretaris 1 LASGAR</p>
				<p>- Kreatif Alphabeta</p>
				<p>- PDK CS League</p>
				<p>- Kreatif Wisgen</p>
				<p>- Dankom OH Fasilkom</p>
			</div>

			<button class="accordion">Prestasi</button>
			<div class="panel">
				<br>
				<p>- Peringkat 1 kelas 3 SMA</p>
				<p>- Peringkat 2 SMP</p>
			</div>

			<script>
				var acc = document.getElementsByClassName("accordion");
				var i;

				for (i = 0; i < acc.length; i++) {
				  acc[i].addEventListener("click", function() {
				    this.classList.toggle("active");
				    var panel = this.nextElementSibling;
				    if (panel.style.maxHeight){
				      panel.style.maxHeight = null;
				    } else {
				      panel.style.maxHeight = panel.scrollHeight + "px";
				    } 
				  });
				}
			</script>
		</div>
	</div>
	<br><br>
</body>
</html>

status/templates/Subscribe.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Berlangganan pada website ini</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
	<link href="https://fonts.googleapis.com/css?family=Handlee" rel="stylesheet">	<!-- font -->
	<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/glacial-indifference" type="text/css"/>
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" href="sweetalert2.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="{% static 'js/subscribe.js'%}"></script>

  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  	<script src="sweetalert2.all.min.js"></script>
	<!-- Optional: include a polyfill for ES6 Promises for IE11 and Android browser -->
	<script src="https://cdn.jsdelivr.net/npm/promise-polyfill"></script>
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
</head>
<body>
	<div>
		<div class="row">
			<br>
		</div>
		<div class="row">
			<h1 class="text-center">Berlangganan</h1>
			<br>
		</div>
	</div>

	<div id="tentangsaya" class="container" >
		<div class="square-service-block tentang">
			<h3 class="text-left" style="font-family: 'GlacialIndifferenceRegular'; font-size: 3vw; color: #ff0055;">Buat akun anda !</h3>
			<br>
			<div class="row">
				<div class="col-4">
					<form method="POST" style="font-size: 20px;">
				            {% csrf_token %}
				            <h4>Nama :</h4>
				            {{ subscriber_form.nama }} <br><br>
				            <h4>Email :</h4>
				            {{ subscriber_form.email }} <br><br>
				            <h4>Password : (5-20 karakter)</h4>
				            {{ subscriber_form.password }} <br>
				            <br>
				            <button id="subscribe" disabled="disabled" class="btn btn-basic button-post" style="color:white; font-size: 15px;">Subscribe</button>
				    </form>
				    <br><br>
				    <a href="{% url 'status:landingpage' %}" style="font-family: 'GlacialIndifferenceRegular'; font-size: 16px;">< Kembali</a>
				</div>
				<div class="col-3">
					<br><br><br><br><br><br>
					<p id="email-message">Email tersebut sudah pernah didaftarkan sebelumnya, silakan daftar dengan email lain</p>
				</div>
			</div>
		</div>

	</div>

	<br><br>
</body>
</html>

store/templates/Buku.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Perpustakaan</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
	<link href="https://fonts.googleapis.com/css?family=Handlee" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Mali" rel="stylesheet">
	<link rel="stylesheet" media="screen" href="https://fontlibrary.org/face/glacial-indifference" type="text/css">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  	<script src="{% static 'js/text.js'%}"></script>
  	<script src="{%static 'js/TextBuku.js'%}"></script>
	
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body style="margin:0;">

	<div class="row">
		<h1 class="text-center">Daftar Buku</h1>
	</div>
	<br><br>
	<div class="row">
		<div class="col-2">
			<p></p>
		</div>
		<div class="col-3">
			<div class="square-service-block box-jumlah-fav">
				<span><a href="{% url 'status:landingpage' %}"><button class="btn btn-default" style="font-family: GlacialIndifferenceRegular; background-color: #ff0055; color: white;">< Beranda</button></a></span>

				{% if user.is_authenticated %}
					<span><i class="fa fa-star" style="font-size:36px;color:yellow; margin-top: 10px; margin-left: 20px;"></i></span> <span style="font-family: GlacialIndifferenceRegular;margin-left: 20px; color: #990033;"> Buku Favorit </span><span><input id="counter" class="btn btn-default" type="button" style="margin-left: 15px; margin-bottom: 5px;" value="{{ counter }}"></input></span>
					<span style="font-family: 'GlacialIndifferenceRegular'; margin-left: 20px; color: #990033; font-style: bold; font-size: 22px;"> Hai, {{ user.username }} </span>
					<span><a href="{% url 'store:logout' %}"><button class="btn btn-default" style="margin-bottom: 10px; font-family: GlacialIndifferenceRegular; background-color: #ff0055; color: white; font-style:italic; margin-left: 170px; ">Logout</button></a></span>
				{% else %}
					<span><a href="{% url 'social:begin' 'google-oauth2' %}"><button class="btn btn-default" style="margin-bottom: 10px; margin-top: 15px; font-family: GlacialIndifferenceRegular; background-color: #ff0055; color: white; font-style:italic; margin-left: 250px; ">Login with Google</button></a></span>
				{% endif %}
			</div>
		</div>
	</div>
	<br><br>

	<div class="row">
		<div class="col-2">
			<p></p>
		</div>
		<div class="col-3">
			<input id="inputan" type="text" name="buku" placeholder="Cari buku" style="width: 250px; height: 30px; border-radius: 15px;">
	        <span><button onclick="book()" id="submit" type="submit" class="btn btn-basic button-post" style="color: white; font-size: 15px; width: 60px; height: 30px; border-radius: 15px;">Cari</button></span>
	    </div>
	</div>
	<br><br>
	<div class="row">
		<div id="list" class="container">
			<div class="square-service-block box-list-buku">
				<table id="table-buku" style="font-family: GlacialIndifferenceRegular;" class="table-condensed">
					<tr style="background-color: #ffb3b3; border-radius: 15px; height: 50px; font-size: 20px;">
						<th style="text-align: center; width: 50px; color: #990033;">No</th>
						<th style="text-align: center; width: 150px; color: #990033;"></th>
						<th style="text-align: center; width: 200px; color: #990033;">Judul</th>
						<th style="text-align: center; width: 400px; color: #990033;">Deskripsi</th>
						<th style="text-align: center;width: 100px; color: #990033;">Tambahkan ke Favorit</th>
					</tr>
				</table>
			</div>
		</div>
	</div>

	<br><br><br>
</body>
</html>